export const QUERY_SET = 'QUERY_SET'
export const QUERY_RESET = 'QUERY_RESET'
export const HISTORY_SET = 'HISTORY_SET'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const HISTORY_FAIL = 'HISTORY_FAIL'