export const COMMUNITY_FETCHING = 'COMMUNITY_FETCHING'
export const COMMUNITY_REFRESHING = 'COMMUNITY_REFRESHING'
export const COMMUNITY_OK = 'COMMUNITY_OK'
export const COMMUNITY_FAIL = 'COMMUNITY_FAIL'