export const SELECT_COMMUNITY_TAG_OK = 'SELECT_COMMUNITY_TAG_OK';
export const SELECT_COMMUNITY_TAG_LOADING = 'SELECT_COMMUNITY_TAG_LOADING';
export const SELECT_COMMUNITY_TAG_FAIL = 'SELECT_COMMUNITY_TAG_FAIL';